spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Laptop-User-DB
    username: postgres
    password: tiger
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

  application:
    name: laptop_store_application

logging:
  level:
    root: INFO


